function exportReport(algorithmName, processes, timeline, metrics) {
  // Get jsPDF constructor from UMD global
  const jsPDFRef = window.jspdf?.jsPDF;
  if (!jsPDFRef) {
    alert("jsPDF failed to load. Check the CDN link in index.html.");
    return;
  }

  const doc = new jsPDFRef({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });
  let y = 14;

  // ---------- Header ----------
  doc.setFontSize(18);
  doc.text("ChronOS - CPU Scheduling Report", 14, y);
  y += 8;

  doc.setFontSize(11);
  doc.text(`Algorithm: ${algorithmName}`, 14, y);
  y += 6;

  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, y);
  y += 10;

  // ---------- Process Table ----------
  doc.setFont("helvetica", "bold");
  doc.text("Processes:", 14, y);
  y += 6;

  doc.setFont("helvetica", "normal");

  const headers = ["PID", "Arrival", "Burst", "Priority"];
  const colWidth = [24, 24, 24, 24];
  let x = 14;

  headers.forEach((h, i) => {
    doc.text(h, x, y);
    x += colWidth[i];
  });

  y += 5;

  processes.forEach((p) => {
    x = 14;
    const row = [p.pid, p.arrival, p.burst, p.priority ?? "-"];
    row.forEach((val, i) => {
      doc.text(String(val), x, y);
      x += colWidth[i];
    });
    y += 5;
  });

  y += 10;

  // ---------- Metrics ----------
  doc.setFont("helvetica", "bold");
  doc.text("Performance Metrics:", 14, y);
  y += 6;

  doc.setFont("helvetica", "normal");

  const metricsList = [
    ["Avg Waiting Time", metrics.avgWaitingTime],
    ["Avg Turnaround Time", metrics.avgTurnaroundTime],
    ["CPU Utilization (%)", metrics.cpuUtilization],
    ["Throughput (proc/unit)", metrics.throughput],
    ["Idle Time (units)", metrics.idleTime],
    ["Context Switches", metrics.contextSwitches],
  ];

  metricsList.forEach(([label, value]) => {
    doc.text(`${label}: ${value}`, 14, y);
    y += 5;
  });

  // ---------- Footer ----------
  y += 12;
  doc.setFontSize(10);
  doc.text("Generated by ChronOS Simulator © 2025", 14, y);

  // ---------- Save ----------
  const fileName = `ChronOS_Report_${algorithmName}_${new Date()
    .toISOString()
    .slice(0, 10)}.pdf`;

  doc.save(fileName);
}

// expose function globally for main.js
window.Report = { exportReport };
